### PR TITLE
fix: search page for non latest doc versions

### LINKED ISSUE #203: Search page is not working with versioned docs
The search bar is working great with versioned docs since v0.27.0, however, the search page is not.

Repro:

1. Open the [*next* version of the example website](https://easyops-cn.github.io/docusaurus-search-local/docs/next/intro/).
2. Click the search bar and enter `intro`.
3. Click the link `See all results` below.
4. Shows `Page not found`.

cc @Cyriuz

### PR DESCRIPTION
**Pull request by Cyriuz**
fixes #203

Sorry for taking a while with this. I figured out the way to use the actual selected version as the useActiveVersion only works on doc pages (internally it just compares the path). However, this causes the test webpage to crash... so I spent yesterday trying to figure out why. After asking for help on the docusaurus discord it turns out that it is somehow because of the pnp build step: 

```
[11:49] Josh-Cena: I have a feeling this has something to do with PnP
[11:49] Josh-Cena: Could you try with node-modules linker?
[11:50] Josh-Cena: I can't remember who was the last to bring it up, but there's a problem with PnP + contexts
[11:52] Josh-Cena: More specifically, theme-common fails to be deduplicated, so the context provider of theme-classic and the context consumer in the search theme are actually two instances, so they fail to pair up
```

After this I tried it in my own non pnp setup and it did indeed work. I tried changing some things to see if I could get it to work but I feel I'm a bit out of my depth here and may need some help. package dependencies seems like a pretty complicated field in its own...

### CODE REVIEW

**Comment by weareoutman** [comment]
I figured out that if we put the `@docusaurus/theme-common` into the peerDependencies of our theme (also add it to the devDependencies), will make it work with P'n'P. At the same time, we also need to explicitly add `@docusaurus/theme-common` to the dependencies of the example website.

I am wondering if it's the correct way, since our user may must manually add `@docusaurus/theme-common` to their website dependencies as we did here.

**Comment by weareoutman** [comment]
> I figured out that if we put the `@docusaurus/theme-common` into the peerDependencies of our theme (also add it to the devDependencies), will make it work with P'n'P. At the same time, we also need to explicitly add `@docusaurus/theme-common` to the dependencies of the example website.
> 
> I am wondering if it's the correct way, since our users may must manually add `@docusaurus/theme-common` to their website dependencies as we did here.

Maybe using peer dependencies is just the correct way, since our users may run into the same issue of duplicate instances of theme-common, if they didn't dedupe correctly.

In npm 7+ (shipped with node 15), npm will install peer dependencies automatically, so I think there will be no troubles these users will encounter. For others (npm <=6, yarn), I will first try to release an alpha version to test if it does work. If it requires an explicit dependencies of theme-common, we should add notice about it in installation section of our docs.

**Comment by Cyriuz** [comment]
Awesome, yeah that sounds good! :D

**Comment by weareoutman** [comment]
This may take a little longer, I got very limit time to this project these days, :(

File: docusaurus-search-local/src/client/theme/SearchBar/SearchBar.tsx [hunk 1]
```diff
@@ -48,9 +49,11 @@ export default function SearchBar({
   let {
     siteConfig: { baseUrl },
   } = useDocusaurusContext();
-  const activeVersion = useActiveVersion();
-  if (activeVersion && !activeVersion.isLast) {
-    baseUrl = activeVersion.path + "/";
+  const { pluginId } = useActivePlugin({failfast: true})!;
```
Comment (weareoutman) [inline docusaurus-search-local/src/client/theme/SearchBar/SearchBar.tsx:52]: Building the example website will fail due to this change.

```
➤ YN0000: [website]: Error: Can't find active docs plugin for "/docusaurus-search-local/404" pathname, while it was expected to be found. Maybe you tried to use a docs feature that can only be used on a docs-related page? Existing docs plugin paths are: /docusaurus-search-local/docs
➤ YN0000: [website]: Error: Can't find active docs plugin for "/docusaurus-search-local/blog" pathname, while it was expected to be found. Maybe you tried to use a docs feature that can only be used on a docs-related page? Existing docs plugin paths are: /docusaurus-search-local/docs
➤ YN0000: [website]: Error: Can't find active docs plugin for "/docusaurus-search-local/blog/archive" pathname, while it was expected to be found. Maybe you tried to use a docs feature that can only be used on a docs-related page? Existing docs plugin paths are: /docusaurus-search-local/docs
➤ YN0000: [website]: Error: Can't find active docs plugin for "/docusaurus-search-local/blog/hello-world" pathname, while it was expected to be found. Maybe you tried to use a docs feature that can only be used on a docs-related page? Existing docs plugin paths are: /docusaurus-search-local/docs
➤ YN0000: [website]: Error: Can't find active docs plugin for "/docusaurus-search-local/blog/hola" pathname, while it was expected to be found. Maybe you tried to use a docs feature that can only be used on a docs-related page? Existing docs plugin paths are: /docusaurus-search-local/docs
➤ YN0000: [website]: Error: Can't find active docs plugin for "/docusaurus-search-local/blog/tags" pathname, while it was expected to be found. Maybe you tried to use a docs feature that can only be used on a docs-related page? Existing docs plugin paths are: /docusaurus-search-local/docs
➤ YN0000: [website]: Error: Can't find active docs plugin for "/docusaurus-search-local/blog/tags/docusaurus" pathname, while it was expected to be found. Maybe you tried to use a docs feature that can only be used on a docs-related page? Existing docs plugin paths are: /docusaurus-search-local/docs
➤ YN0000: [website]: Error: Can't find active docs plugin for "/docusaurus-search-local/blog/tags/facebook" pathname, while it was expected to be found. Maybe you tried to use a docs feature that can only be used on a docs-related page? Existing docs plugin paths are: /docusaurus-search-local/docs
➤ YN0000: [website]: Error: Can't find active docs plugin for "/docusaurus-search-local/blog/tags/hello" pathname, while it was expected to be found. Maybe you tried to use a docs feature that can only be used on a docs-related page? Existing docs plugin paths are: /docusaurus-search-local/docs
➤ YN0000: [website]: Error: Can't find active docs plugin for "/docusaurus-search-local/blog/tags/hola" pathname, while it was expected to be found. Maybe you tried to use a docs feature that can only be used on a docs-related page? Existing docs plugin paths are: /docusaurus-search-local/docs
➤ YN0000: [website]: Error: Can't find active docs plugin for "/docusaurus-search-local/blog/welcome" pathname, while it was expected to be found. Maybe you tried to use a docs feature that can only be used on a docs-related page? Existing docs plugin paths are: /docusaurus-search-local/docs
➤ YN0000: [website]: Error: Can't find active docs plugin for "/docusaurus-search-local/blog/writing-good-unit-tests" pathname, while it was expected to be found. Maybe you tried to use a docs feature that can only be used on a docs-related page? Existing docs plugin paths are: /docusaurus-search-local/docs
➤ YN0000: [website]: Error: Can't find active docs plugin for "/docusaurus-search-local/search" pathname, while it was expected to be found. Maybe you tried to use a docs feature that can only be used on a docs-related page? Existing docs plugin paths are: /docusaurus-search-local/docs
➤ YN0000: [website]: Error: Can't find active docs plugin for "/docusaurus-search-local/" pathname, while it was expected to be found. Maybe you tried to use a docs feature that can only be used on a docs-related page? Existing docs plugin paths are: /docusaurus-search-local/docs
```

Comment (weareoutman) [reply docusaurus-search-local/src/client/theme/SearchBar/SearchBar.tsx]: Fixed that. How ever, I think we didn't fix #211

**Comment by weareoutman** [comment]
> 

Tests passed, I think we're ready to go

**Review by weareoutman — APPROVED** [review]

**Comment by slorber** [comment]
Not sure why yet but it looks like this code makes Docusaurus fail on latest canary (but works on latest beta.21).

https://github.com/facebook/docusaurus/issues/7686#issuecomment-1172377776

Currently investigating

File: docusaurus-search-local/src/client/theme/SearchBar/SearchBar.tsx [hunk 2]
```diff
@@ -10,7 +10,8 @@ import useDocusaurusContext from "@docusaurus/useDocusaurusContext";
 import ExecutionEnvironment from "@docusaurus/ExecutionEnvironment";
 import { useHistory, useLocation } from "@docusaurus/router";
 import { translate } from "@docusaurus/Translate";
-import { useActiveVersion } from '@docusaurus/plugin-content-docs/client';
+import { useDocsPreferredVersion } from "@docusaurus/theme-common";
```
Comment (slorber) [inline docusaurus-search-local/src/client/theme/SearchBar/SearchBar.tsx:13]: We have moved this export to an internal entrypoint

```js
import {
  useDocsPreferredVersion,
} from '@docusaurus/theme-common/internal';
```

This also means that technically we are not 100% ready to consider this API to be part of our public API surface and make no breaking changes on it 😅 

But this can be discussed if you don't have a better choice than using it, and in practice we may not break it

Comment (Cyriuz) [reply docusaurus-search-local/src/client/theme/SearchBar/SearchBar.tsx:13]: I couldn't find any other way to do it so it is either that or if you know of any other, supported, way of getting the selected version?

Comment (slorber) [reply docusaurus-search-local/src/client/theme/SearchBar/SearchBar.tsx:13]: Will move useDocsPreferredVersion to our public api

Even though we may do a breaking change later, it will be clearly highlighted in a major release blog post
