### PR TITLE
fix: use debug instead of console.error for useDocsPreferredVersion

### LINKED ISSUE #242: Build output is spammed with `useDocsPreferredVersion ReactContextError` when not using versioned docs
When not using versions, the console log output get *spammed* by error log messages like this one:

```
useDocsPreferredVersion ReactContextError
    at useDocsPreferredVersionContext (main:16775:353)
    at useDocsPreferredVersion (main:16781:155)
    at SearchBar (main:16309:80)
    at d (main:141143:498)
    at bb (main:141146:16)
    at a.b.render (main:141152:43)
    at a.b.read (main:141151:83)
    at Object.exports.renderToString (main:141162:138)
    at doRender (main:14280:417)
    at async serverEntry_render (main:14272:290) {
  message: 'Hook useDocsPreferredVersionContext is called outside the <DocsPreferredVersionContextProvider>. '
}
```

This is because of this line:

https://github.com/easyops-cn/docusaurus-search-local/blob/f435c2ca6e46ad637f53d049f9af60513888dc48/docusaurus-search-local/src/client/theme/SearchBar/SearchBar.tsx#L85

As well as this one:

https://github.com/easyops-cn/docusaurus-search-local/blob/f435c2ca6e46ad637f53d049f9af60513888dc48/docusaurus-search-local/src/client/theme/SearchPage/SearchPage.tsx#L62

This is problematic for any documentation websites, even small ones, as they probably get one exception per documentation page, leading to a lot of noise that may make the real cause of a build failure much harder to find.

These should probably not be logged as errors in my opinion (as they do not impact the build process and are "normal") and should be changed to be debug messages instead to leave a cleaner build output.

### PR DESCRIPTION
**Pull request by utybo**
Fixes #242 

Not sure if this is the best approach but it sure works

### CODE REVIEW

File: docusaurus-search-local/src/client/theme/SearchBar/SearchBar.tsx [hunk 1]
```diff
@@ -82,7 +83,7 @@ export default function SearchBar({
   } catch (e: unknown) {
     if (indexDocs) {
       if (e instanceof ReactContextError) {
-        console.error("useDocsPreferredVersion", e);
+        debug("SearchBar")("useDocsPreferredVersion", e);
```
Comment (weareoutman) [inline docusaurus-search-local/src/client/theme/SearchBar/SearchBar.tsx:86]: I think we'd better to just remove the error log. There's no need to introduce a new library on client side

Comment (utybo) [reply docusaurus-search-local/src/client/theme/SearchBar/SearchBar.tsx]: Fair enough, I've removed the error logs entirely. :+1:

Comment (utybo) [reply docusaurus-search-local/src/client/theme/SearchBar/SearchBar.tsx]: Fair enough, I've removed the error log 👍🏻 (sorry about the double comment, I tried replying via VS Code's GitHub extension and it ended up creating a new thread instead of replying to your message 😕 ).

**Review by weareoutman — APPROVED** [review]
